text utilities
rajaranjanmr/component_library_ui_framework pull request #5
Opened 2022-02-16 20:57 UTC by rajaranjanmr

2022-02-18 06:20 UTC, manish-GH requested changes
Also please add the navigation function for the sidebar.

2022-02-18 06:20 UTC, manish-GH commented on buttons/button.css
> +    cursor: pointer;
It would be better to add cursor: pointer on button hover

2022-02-18 06:20 UTC, manish-GH commented on buttons/button.css
> +    cursor: pointer;
same here, add this on hover

2022-02-18 06:20 UTC, manish-GH commented on cards/card1.css
> +    bottom:45px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on cards/card1.css
> +    background-color: rgb(191, 194, 5);
use variables for colors

2022-02-18 06:20 UTC, manish-GH commented on cards/card1.css
> +    background-color: rgb(57, 8, 104);
use variable

2022-02-18 06:20 UTC, manish-GH commented on cards/cardWithBadge.css
> +bottom:45px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on cards/cardWithBadge.css
> +bottom:70px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on cards/cardwithDismiss.css
> +background-color: #082032;
use variable

2022-02-18 06:20 UTC, manish-GH commented on cards/cardwithShadow.css
> +    bottom:45px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on cards/cardwithhorizontal.css
> +    background-color: aliceblue;
use variable

2022-02-18 06:20 UTC, manish-GH commented on cards/cardwithoverlay.css
> +bottom:45px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on cards/cardwithtext.css
> +min-height:255px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on inputBox/index.css
> +    font-size:20px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on inputBox/index.css
> +    font-size:20px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on inputBox/index.css
> +    right: -23px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on inputBox/index.css
> +    font-size:20px;
use rem

2022-02-18 06:20 UTC, manish-GH commented on textstyles/texts.html
> +        <div class="h1">
I don't think you need both div and h tags. You can use either 

<div class="h1">Heading 1</div>

or reset the h1 tag according to your need and just use
<h1>Heading 1</h1>

Same for all the other H tags

2022-02-18 06:20 UTC, manish-GH commented on textstyles/texts.html
> +        <div class="h5">
the class should be h6

2022-02-18 06:20 UTC, manish-GH commented on buttons/button.html
> +        <div class="primary-btn btns">
For the class names, we were suggested to his convention
btn btn-primary

Follow the same for other buttons as well

2022-02-18 16:12 UTC, manish-GH requested changes

2022-02-18 16:12 UTC, manish-GH commented on inputBox/index.css
> +    background-color: #041562;
use variables for colors

2022-02-18 16:12 UTC, manish-GH commented on cards/card1.css
> +    background-color: green;
use variable

2022-02-18 16:12 UTC, manish-GH commented on cards/card1.css
> +    background-color:#390868;
use variable

2022-02-18 16:12 UTC, manish-GH commented on cards/cardwithShadow.css
> +    bottom:70px;
use rem

2022-02-18 16:12 UTC, manish-GH commented on cards/cardwithoverlay.css
> +background-color: #082032;
use variable

2022-02-18 16:12 UTC, manish-GH commented on inputBox/index.css
> +    background-color: #f2f2f2;
use variable

2022-02-18 16:12 UTC, manish-GH commented on inputBox/index.css
> +    background-color: #45a049;
use variable

2022-02-18 16:12 UTC, manish-GH commented on inputBox/index.css
> +    border-color:tomato;
use variable

2022-02-18 16:12 UTC, manish-GH commented on inputBox/index.css
> +    border-color:tomato;
use variable

2022-02-19 04:45 UTC, manish-GH approved these changes
You have missed some, have a look at line-29 in inputBox/index.css file and line-12 in textstyles/text.html file.

Everything else seems fine, can be merged

2022-02-19 05:41 UTC, sri-rishi requested changes

2022-02-19 05:41 UTC, sri-rishi commented on badges/badgesAvtaar.css
remove  extra spaces

2022-02-19 05:41 UTC, sri-rishi commented on cards/card1.html
> +    </div>
if not necessary remove comments

2022-02-19 05:41 UTC, sri-rishi commented on cards/cardWithBadge.css
> +
give tab spacing here hard to differentiate between properties and class name

2022-02-19 05:41 UTC, sri-rishi commented on responsive images/responsiveimage1.css
> +  gap:1rem;
Be consistent with spacing

2022-02-19 05:41 UTC, sri-rishi commented on responsive images/round.html
> +    text-align: center;
keep styles in separate  file

2022-02-19 06:42 UTC, sri-rishi approved these changes

2022-02-19 07:53 UTC, merged